service: octosign-lotl-proxy

plugins:
    - serverless-offline
    - serverless-api-compression

custom:
    bucket: octosign-lotl-proxy-cache
    contentCompression: 1024

provider:
    name: aws
    runtime: nodejs12.x
    profile: default
    region: ${opt:region, 'eu-central-1'}
    memorySize: 512
    timeout: 300

    iamRoleStatements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
    refresh:
        handler: handler.refresh
        events:
            - schedule: rate(6 hours)
        environment:
            BUCKET: ${self:custom.bucket}

    fetch:
        handler: handler.fetch
        events:
            - http: get fetch
            custom:
                contentCompression: 1024
        environment:
            BUCKET: ${self:custom.bucket}
