service: octosign-lotl-proxy

plugins:
    - serverless-offline

custom:
    bucket: octosign-lotl-proxy-cache

provider:
    name: aws
    runtime: nodejs14.x
    profile: personal
    region: ${opt:region, 'eu-central-1'}
    memorySize: 512
    timeout: 300
    apiGateway:
        minimumCompressionSize: 1024

    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:PutObject
                  Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
    refresh:
        handler: handler.refresh
        events:
            - schedule: rate(6 hours)
        environment:
            BUCKET: ${self:custom.bucket}

    fetch:
        handler: handler.fetch
        events:
            - http: GET /fetch
        environment:
            BUCKET: ${self:custom.bucket}
